/// <reference types="next/image-types/global" />

// Declares what `import portrait from '../../public/vladimir-shikov.jpg'` is:
// a `StaticImageData`, not an error.
//
// Next writes the same reference into `next-env.d.ts`, but that file is
// generated by `next dev` or `next build` and is git-ignored, as Next intends.
// The `typecheck` job runs `tsc --noEmit` on a fresh clone with no build before
// it, so on CI the declaration simply was not there — a developer who had ever
// run the app locally could not reproduce the failure.
//
// It went unnoticed until the portrait became the first static image the app
// imports. This file is committed precisely so the type does not depend on
// whether someone happened to build first.
